In [1]:
import numpy as np 

In [2]:
a=np.array([[1,2], [1.0]])
print(a)

[list([1, 2]) list([1.0])]


/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [3]:
type(a)

numpy.ndarray

In [4]:
A=np.array([[1.2]])

In [5]:
print(A)

[[1.2]]


In [6]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
a=np.array([1,3,5,7])
b=np.array([1,3,5,7])
c=a+b
print(c)

[ 2  6 10 14]


In [8]:
a=np.array([1,3,5,7])
b=np.array([[1],[3],[5],[7]])
c=a+b
print(c)

[[ 2  4  6  8]
 [ 4  6  8 10]
 [ 6  8 10 12]
 [ 8 10 12 14]]


In [9]:
a=np.array([[1,3],[2,5]])
b=np.array([[9,-3],[3,6]])
c=a+b
print(c)

[[10  0]
 [ 5 11]]


In [10]:
v=np.array([1,2,3])
print(v.transpose())

[1 2 3]


In [11]:
v=np.array([[1],[2],[3]])
print(v.transpose())

[[1 2 3]]


In [12]:
V1=np.array([4,3,2])

In [13]:
c=2
print("The vector V1 = ",V1)

The vector V1 =  [4 3 2]


In [14]:
import numpy as np
a=np.array([2,4,8,7,7])
b=np.array([2,3,1,7,8])
opab=np.outer(a,b)
opba=np.outer(b,a)
print('\n\n--A--\n',a)
print('\n\n--B--\n',b)
print('\n\nOuter productasA.B:',opab)



--A--
 [2 4 8 7 7]


--B--
 [2 3 1 7 8]


Outer productasA.B: [[ 4  6  2 14 16]
 [ 8 12  4 28 32]
 [16 24  8 56 64]
 [14 21  7 49 56]
 [14 21  7 49 56]]


In [15]:
A=np.array([[3,6,7],[5,-3,0]])
B=np.array([[1,1],[2,1],[3,-3]])
D=A.dot(B)
print("D =",D)


D = [[ 36 -12]
 [ -1   2]]


In [16]:
P=np.array([[3,6,7],[5,-3,0]])
Q=np.array([[1,1,2],[2,1,4]])
R=P*Q

In [17]:
print(R)

[[ 3  6 14]
 [10 -3  0]]


In [18]:
np.shape(R)

(2, 3)

In [19]:
np.shape(D)

(2, 2)

In [20]:
import numpy as np
b=np.array([2,3,1,7,8])
C=print(b.transpose())

[2 3 1 7 8]


In [21]:
a=np.array([2,3,1,7,8])

In [22]:
a=np.array([3.0,2.0,4.0,5.0])

b=np. transpose(a)
m=np.inner(a,b)

print(m)

54.0


In [23]:
b=([2,3,1,7,8])

In [24]:
import numpy as np
v1=np.array([4,5,6,7])
v2=np.array([4],[5],[6],[7])
v3=(v1.transpose())
R1=v1.dot(v2)
print(type(R1))

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [25]:
import numpy as np
v1=np.array([4,5,6,7])
print(np.shape(v1))
v2=np.array([[4],[5],[6],[7]])
print(np.shape(v2))
r1=v2.dot(v1)
print(r1.shape)

(4,)
(4, 1)


ValueError: shapes (4,1) and (4,) not aligned: 1 (dim 1) != 4 (dim 0)

In [26]:
import numpy as np
x=np.arange(9).reshape((3,3))             #array=[[0,1,2][3,4,5],[6,7,8]]
 
print(np.diag(x))
np.diag(x,k=1)
np.diag(x,k=-1) 
y=np.diag(np.diag(x))                   #array=[[0,1,2][3,4,5],[6,7,8]]
z=np.diag([5,6,7])  #array=[[0,5,0][0,6,0],[0,0,7]]
print(y)
print(z)

[0 4 8]
[[0 0 0]
 [0 4 0]
 [0 0 8]]
[[5 0 0]
 [0 6 0]
 [0 0 7]]


In [27]:
# diagonal Martix
import numpy as np
x = np.arange(9).reshape((3,3)) 
print("x:",x)
#np.diag(x) #array([0, 4, 8])
print("x1:",np.diag(x))
print("x2:",np.diag(x, k=1)) # array([1, 5])
print("x3:",np.diag(x, k=-1)) #array([3, 7])

y = np.diag(np.diag(x)) 
print("y:",y)
z = np.diag([5, 6, 7]) 
print("z:",z)

x: [[0 1 2]
 [3 4 5]
 [6 7 8]]
x1: [0 4 8]
x2: [1 5]
x3: [3 7]
y: [[0 0 0]
 [0 4 0]
 [0 0 8]]
z: [[5 0 0]
 [0 6 0]
 [0 0 7]]


In [28]:
import numpy as np
I=np.eye(4)
print("\n--I(4*4)--\n",I)
k=14
Ik=I
for i in range(14):
 Ik=I*Ik
 
print('\n\n--I(I*K)--\n',Ik)


--I(4*4)--
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


--I(I*K)--
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
import numpy as np
I=np.eye(4)
print("\n--I(4*4)--\n",I)
k=14
Ik=I
for i in range(14):
 Ik=I*Ik
print(Ik)


--I(4*4)--
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
import numpy as np
V1=[4,5,6,7]
V2=[[4],[5],[6],[7]]
V3=V1.transpose()
R1=V1.dot(V2)
print(type(R1))
print(R1)
R2=V1.dot(V1)
print(type(R2))
print(R2)

AttributeError: 'list' object has no attribute 'transpose'

In [35]:
import numpy as np
M=np.array([[2,3,4],[3,5,8],[4,8,7]])
print("__matrixA__\n",M)
ai=np.linalg.inv(M)
print('\n\nInverse of A as____\n',ai)

__matrixA__
 [[2 3 4]
 [3 5 8]
 [4 8 7]]


Inverse of A as____
 [[ 3.22222222 -1.22222222 -0.44444444]
 [-1.22222222  0.22222222  0.44444444]
 [-0.44444444  0.44444444 -0.11111111]]


In [41]:
import numpy as np
M=np.array([[0,0,0],[0,0,0],[0,0,0]])
print("__matrixA__\n",M)
ai=np.linalg.inv(M)
print('\n\nInverse of A as____\n',ai)

__matrixA__
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


LinAlgError: Singular matrix